version: "3.7"
services:
  mysqldb:
    container_name: tech-challenge-group-57-producao-mysql
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - java-service-network
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: techchallenge
      MYSQL_PASSWORD: techchallenge
      MYSQL_ROOT_PASSWORD: techchallenge

  app:
    build: .
    container_name: tech-challenge-group-57-producao-api
    restart: always
    ports:
      - 8080:8080
    networks:
      - java-service-network
    environment:
      DATABASE_URL: jdbc:mysql://mysqldb:3306/mydb?allowPublicKeyRetrieval=true
      DATABASE_USER: techchallenge
      DATABASE_PASSWORD: techchallenge
      DATABASE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

networks:
  java-service-network:

volumes:
  mysql-data:
